"""
Orchestrator: pulls BTC/ETH derivative data from public APIs -> computes levels ->
generates CryptoLevels_auto.pine (paste once into the TradingView Pine editor).

Crypto clone of gamma-seed/build_seed.py, same operating model:
  1x daily:  python build_seed.py   -> paste the generated Pine -> FREEZE.
  Structure map 7-45 DTE (stable daily lines) vs near map 0-5 DTE (daily weather),
  identical split to the index pipeline.

Data (all public, no keys):
  Deribit  - option board (OI + mark IV) -> GEX flip/walls/max pain/EM + vanna/charm
  Binance  - funding (real prints), OI + 24h delta, long/short ratios -> label text
  OKX      - recent liquidation prints -> clustered context levels (PAST events,
             not a forward heatmap - Coinglass-style forward maps are estimates
             everywhere; we only draw what actually happened)

Fail-soft: every provider block degrades to zeros / yesterday's stored levels
instead of killing the build. Each day = one row per coin in data/levels_*.csv
(idempotent: today's date is replaced on re-run).
"""
from datetime import date
from pathlib import Path

import pandas as pd

import gex
import providers as P

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
DATA.mkdir(exist_ok=True)

STRUCT_MIN_DTE = 7   # structure map: same window as the index pipeline (7-45)
STRUCT_MAX_DTE = 45
NEAR_MAX_DTE = 5     # near map: 0-5 DTE dailies/weeklies

#          coin   Binance-perp  OKX-underlying
COINS = [("BTC", "BTCUSDT", "BTC-USDT"),
         ("ETH", "ETHUSDT", "ETH-USDT")]

FIELDS = ["FLIP", "CW", "PW", "CW2", "PW2", "NCW", "NPW", "NF", "MP", "SPOT",
          "EM", "GEXBN", "VAN", "VANK", "CHM", "CHMK",
          "FUND", "OIU", "OID", "LSR", "TLS",
          "LQ1", "LQ1D", "LQ2", "LQ2D", "LQ3", "LQ3D"]


def g(lv, key):
    return (lv or {}).get(key) or 0.0


# ------------------------------------------------------------ Pine template ----
# Deliberately pure ASCII (the .bat ritual copies via `clip` = ANSI codepage).
AUTO_TEMPLATE = r'''//@version=6
// Crypto Levels (Auto) [KruegerAlgorithms] - AUTO-GENERATED by build_seed.py (DO NOT edit)
// STRUCTURE map (7-45 DTE, Deribit options) = thick lines | NEAR map (0-5 DTE) = dotted
// Extras: Binance derivatives snapshot in the label (funding/OI/positioning) and
// recent OKX liquidation clusters as dotted lines (PAST forced flow, not a forecast).
// All levels are model estimates on the dealer-sign assumption - context, not signals.
// Daily: `python build_seed.py` -> paste the whole file into the Pine editor -> Save. Freeze.
indicator("Crypto Levels (Auto) [KruegerAlgorithms]", overlay = true)

// ===== DAILY LEVELS in USD (auto-generated __DATE__) =====
__LEVELS__
// =========================================================

coinIn     = input.string("Auto", "Coin", options = ["Auto", "BTC", "ETH"])
offset     = input.float(0.0, "Manual offset (USD, broker basis)")
neutralPct = input.float(0.3, "Flip zone (+/- %)", minval = 0.05, step = 0.05)
showReg    = input.bool(true, "Regime background (green/red/grey)")

grpS = "STRUCTURE map (7-45 DTE) - stable daily lines"
showFlip = input.bool(true,  "FLIP - yellow, thick",                      group = grpS)
showCW   = input.bool(true,  "CALL WALL - red, thick",                    group = grpS)
showPW   = input.bool(true,  "PUT WALL - green, thick",                   group = grpS)
showCW2  = input.bool(true,  "CALL WALL 2 (strike shelf) - red, dashed",  group = grpS)
showPW2  = input.bool(true,  "PUT WALL 2 (strike shelf) - green, dashed", group = grpS)

grpN = "NEAR map (0-5 DTE) - daily weather/pinning"
showNCW  = input.bool(true,  "0DTE CALL WALL - orange, dotted",           group = grpN)
showNPW  = input.bool(true,  "0DTE PUT WALL - teal, dotted",              group = grpN)
showNF   = input.bool(false, "0DTE FLIP - yellow, dotted",                group = grpN)

grpX = "Other"
showEM   = input.bool(true,  "EXPECTED MOVE +/-1 day - blue, dotted",     group = grpX)
showMP   = input.bool(false, "MAX PAIN - grey, dotted",                   group = grpX)

grpV = "FLOW & VOL (context, unvalidated - not a trade signal)"
showVanna = input.bool(true,  "VANNA strike - purple, dotted",            group = grpV)
showCharm = input.bool(true,  "CHARM strike - aqua, dotted",              group = grpV)
showDvol  = input.bool(true,  "DVOL regime in label (DERIBIT:DVOL)",      group = grpV)

grpL = "LIQUIDATIONS (recent OKX prints - past flow, not a heatmap)"
showLiq  = input.bool(true,  "Liq clusters - lime = short-liqs, maroon = long-liqs", group = grpL)
showDer  = input.bool(true,  "Funding / OI / L-S line in label",          group = grpL)

t = str.upper(syminfo.ticker)
detect() =>
    r = "NONE"
    if str.contains(t, "BTC") or str.contains(t, "XBT")
        r := "BTC"
    else if str.contains(t, "ETH")
        r := "ETH"
    r
sel = coinIn == "Auto" ? detect() : coinIn

pick(b, e) => sel == "BTC" ? b : sel == "ETH" ? e : 0.0
off(x) => x > 0 ? x + offset : x

flip  = off(pick(BTC_FLIP, ETH_FLIP))
cw    = off(pick(BTC_CW,   ETH_CW))
pw    = off(pick(BTC_PW,   ETH_PW))
cw2   = off(pick(BTC_CW2,  ETH_CW2))
pw2   = off(pick(BTC_PW2,  ETH_PW2))
ncw   = off(pick(BTC_NCW,  ETH_NCW))
npw   = off(pick(BTC_NPW,  ETH_NPW))
nflip = off(pick(BTC_NF,   ETH_NF))
mp    = off(pick(BTC_MP,   ETH_MP))
spotL = pick(BTC_SPOT, ETH_SPOT)
em    = pick(BTC_EM,   ETH_EM)
gexbn = pick(BTC_GEXBN, ETH_GEXBN)
van   = pick(BTC_VAN,  ETH_VAN)      // USD millions, dealer-sign convention
vank  = off(pick(BTC_VANK, ETH_VANK))
chm   = pick(BTC_CHM,  ETH_CHM)
chmk  = off(pick(BTC_CHMK, ETH_CHMK))
fund  = pick(BTC_FUND, ETH_FUND)     // % per 8h funding period (Binance)
oiu   = pick(BTC_OIU,  ETH_OIU)      // open interest, $ bn
oid   = pick(BTC_OID,  ETH_OID)      // OI change 24h, %
lsr   = pick(BTC_LSR,  ETH_LSR)      // global long/short account ratio
tls   = pick(BTC_TLS,  ETH_TLS)      // top-trader position ratio
lq1   = off(pick(BTC_LQ1, ETH_LQ1))
lq1d  = pick(BTC_LQ1D, ETH_LQ1D)
lq2   = off(pick(BTC_LQ2, ETH_LQ2))
lq2d  = pick(BTC_LQ2D, ETH_LQ2D)
lq3   = off(pick(BTC_LQ3, ETH_LQ3))
lq3d  = pick(BTC_LQ3D, ETH_LQ3D)

// ---- DVOL regime (yesterday's daily close = confirmed, no repaint) ----
// Tertiles over the last 250 daily bars, same read as the VIX block in the
// index tool: high/rising -> decision tilt, low/falling -> chop tilt.
dvolSym = sel == "ETH" ? "DERIBIT:ETHDVOL" : "DERIBIT:DVOL"
[dv1, dv2, dp33, dp67] = request.security(dvolSym, "D",
     [close[1], close[2],
      ta.percentile_linear_interpolation(close[1], 250, 33.333),
      ta.percentile_linear_interpolation(close[1], 250, 66.667)],
     ignore_invalid_symbol = true)
dvReg  = na(dv1) or na(dp33) ? "n/a" : dv1 <= dp33 ? "LOW" : dv1 >= dp67 ? "HIGH" : "MID"
dvDir  = na(dv1) or na(dv2) ? "" : dv1 > dv2 + 0.05 ? "rising" : dv1 < dv2 - 0.05 ? "falling" : "flat"
dvTilt = dvReg == "n/a" ? "" :
     (dvReg == "HIGH" or dvDir == "rising") ? "decision tilt (trend/whipsaw, little chop)" :
     (dvReg == "LOW" and dvDir != "rising") ? "chop tilt" : "neutral"

distPct = flip > 0 ? (close - flip) / flip * 100 : na
reg = flip <= 0 ? -99 : math.abs(distPct) < neutralPct ? 0 : distPct > 0 ? 1 : -1
bgcolor(showReg and reg != -99 ? (reg == 1 ? color.new(color.green, 93) : reg == -1 ? color.new(color.red, 93) : color.new(color.gray, 90)) : na)

levTime = timestamp("GMT", LEV_Y, LEV_M, LEV_D, 23, 59)
isStale = (timenow - levTime) > 1000 * 60 * 60 * 36

var line  lF = na, var line lC = na, var line lP = na, var line lC2 = na, var line lP2 = na
var line  lNC = na, var line lNP = na, var line lNF = na, var line lM = na
var line  lE1 = na, var line lE2 = na
var line  lVA = na, var line lCH = na
var line  lL1 = na, var line lL2 = na, var line lL3 = na
var label lab = na
liqCol(d) => d > 0 ? color.new(color.lime, 40) : color.new(color.maroon, 30)
if barstate.islast
    line.delete(lF), line.delete(lC), line.delete(lP), line.delete(lC2), line.delete(lP2)
    line.delete(lNC), line.delete(lNP), line.delete(lNF), line.delete(lM)
    line.delete(lE1), line.delete(lE2)
    line.delete(lVA), line.delete(lCH)
    line.delete(lL1), line.delete(lL2), line.delete(lL3)
    label.delete(lab)
    x1 = bar_index - 400
    if showFlip and flip > 0
        lF := line.new(x1, flip, bar_index, flip, color = color.yellow, width = 2, extend = extend.right)
    if showCW and cw > 0
        lC := line.new(x1, cw, bar_index, cw, color = color.red, width = 2, extend = extend.right)
    if showPW and pw > 0
        lP := line.new(x1, pw, bar_index, pw, color = color.green, width = 2, extend = extend.right)
    if showCW2 and cw2 > 0
        lC2 := line.new(x1, cw2, bar_index, cw2, color = color.new(color.red, 45), width = 1, extend = extend.right, style = line.style_dashed)
    if showPW2 and pw2 > 0
        lP2 := line.new(x1, pw2, bar_index, pw2, color = color.new(color.green, 45), width = 1, extend = extend.right, style = line.style_dashed)
    if showNCW and ncw > 0
        lNC := line.new(x1, ncw, bar_index, ncw, color = color.orange, width = 1, extend = extend.right, style = line.style_dotted)
    if showNPW and npw > 0
        lNP := line.new(x1, npw, bar_index, npw, color = color.teal, width = 1, extend = extend.right, style = line.style_dotted)
    if showNF and nflip > 0
        lNF := line.new(x1, nflip, bar_index, nflip, color = color.new(color.yellow, 35), width = 1, extend = extend.right, style = line.style_dotted)
    if showMP and mp > 0
        lM := line.new(x1, mp, bar_index, mp, color = color.gray, width = 1, extend = extend.right, style = line.style_dotted)
    if showEM and em > 0 and spotL > 0
        lE1 := line.new(x1, spotL + em + offset, bar_index, spotL + em + offset, color = color.new(color.blue, 55), width = 1, extend = extend.right, style = line.style_dotted)
        lE2 := line.new(x1, spotL - em + offset, bar_index, spotL - em + offset, color = color.new(color.blue, 55), width = 1, extend = extend.right, style = line.style_dotted)
    if showVanna and vank > 0
        lVA := line.new(x1, vank, bar_index, vank, color = color.new(color.purple, 40), width = 1, extend = extend.right, style = line.style_dotted)
    if showCharm and chmk > 0
        lCH := line.new(x1, chmk, bar_index, chmk, color = color.new(color.aqua, 45), width = 1, extend = extend.right, style = line.style_dotted)
    if showLiq and lq1 > 0
        lL1 := line.new(x1, lq1, bar_index, lq1, color = liqCol(lq1d), width = 1, extend = extend.right, style = line.style_dotted)
    if showLiq and lq2 > 0
        lL2 := line.new(x1, lq2, bar_index, lq2, color = liqCol(lq2d), width = 1, extend = extend.right, style = line.style_dotted)
    if showLiq and lq3 > 0
        lL3 := line.new(x1, lq3, bar_index, lq3, color = liqCol(lq3d), width = 1, extend = extend.right, style = line.style_dotted)
    regTxt = reg == 1 ? "LONG GAMMA (pin/reversion)" : reg == -1 ? "SHORT GAMMA (trend/amplify)" : reg == 0 ? "FLIP ZONE (no signal)" : "no data"
    flowTxt = (van != 0.0 or chm != 0.0) ?
         "\nVanna " + (van > 0 ? "+" : "") + str.tostring(van, "#.#") + "M (vol down = " + (van > 0 ? "BUY" : "SELL") + ")" + (vank > 0 ? " @" + str.tostring(vank, format.mintick) : "") +
         "  |  Charm " + (chm > 0 ? "+" : "") + str.tostring(chm, "#.#") + "M (" + (chm > 0 ? "time = buy support" : "time = sell pressure") + ")" + (chmk > 0 ? " @" + str.tostring(chmk, format.mintick) : "") : ""
    derTxt = showDer and (fund != 0.0 or oiu != 0.0) ?
         "\nFunding " + (fund > 0 ? "+" : "") + str.tostring(fund, "#.####") + "%/8h  |  OI " + str.tostring(oiu, "#.##") + "bn$ (" + (oid > 0 ? "+" : "") + str.tostring(oid, "#.#") + "% 24h)" + (lsr > 0 ? "  |  L/S " + str.tostring(lsr, "#.##") : "") + (tls > 0 ? "  top " + str.tostring(tls, "#.##") : "") : ""
    dvTxt = showDvol and dvReg != "n/a" ?
         "\nDVOL " + str.tostring(dv1, "#.#") + " (" + dvReg + ", " + dvDir + ") -> " + dvTilt : ""
    txt = sel + " - " + regTxt + (flip > 0 ? "  Flip " + str.tostring(flip, format.mintick) + " (" + str.tostring(distPct, "#.##") + "%)" : "") + (gexbn != 0.0 ? "  GEX " + (gexbn > 0 ? "+" : "") + str.tostring(gexbn, "#.##") + "bn$/1%" : "") + flowTxt + derTxt + dvTxt + "\nLevels as of " + LEV_DATE + (isStale ? "  !! STALE - run build_seed !!" : "")
    lab := label.new(bar_index, high, txt, style = label.style_label_left, color = isStale ? color.new(color.orange, 10) : reg == 1 ? color.new(color.green, 25) : reg == -1 ? color.new(color.red, 25) : color.new(color.gray, 25), textcolor = color.white, size = size.small)

// ===== ALERTS (selectable in the alert dialog) =====
alertcondition(ta.crossover(close, flip),  "Crypto: Flip cross UP",   "Spot crosses the gamma flip UPWARD -> towards long gamma/pinning")
alertcondition(ta.crossunder(close, flip), "Crypto: Flip cross DOWN", "Spot crosses the gamma flip DOWNWARD -> short gamma/amplify")
alertcondition(ta.crossunder(close, pw),   "Crypto: Put wall BREAK",  "Put wall broken -> trapdoor open (amplify risk)")
alertcondition(ta.crossover(close, pw),    "Crypto: Put wall RECLAIM", "Put wall reclaimed from below -> reversal signature (dealer buybacks)")
alertcondition(ta.crossover(close, cw),    "Crypto: Call wall break UP", "Call wall exceeded -> usually magnet/pin, rarely follow-through")
'''

assert all(ord(c) < 128 for c in AUTO_TEMPLATE), "template must stay pure ASCII"


def gen_auto_pine(levels, today, note=""):
    lines = []
    for coin, _, _ in COINS:
        v = {f: 0.0 for f in FIELDS}
        v.update(levels.get(coin, {}))
        for f in FIELDS:
            lines.append(f"{coin}_{f} = {v[f]:.4f}")
    lines.append(f'LEV_DATE = "{today}{note}"')
    lines.append(f"LEV_Y = {today.year}")
    lines.append(f"LEV_M = {today.month}")
    lines.append(f"LEV_D = {today.day}")
    pine = AUTO_TEMPLATE.replace("__LEVELS__", "\n".join(lines)).replace(
        "__DATE__", str(today))
    out = ROOT / "CryptoLevels_auto.pine"
    out.write_text(pine, encoding="ascii")
    return out


# ------------------------------------------------------------- persistence ----
def store_levels(coin, today, vals):
    """One row per day per coin, idempotent (today's row is replaced)."""
    f = DATA / f"levels_{coin}.csv"
    row = {"date": str(today), **vals}
    if f.exists():
        df = pd.read_csv(f)
        df = df[df["date"] != str(today)]
        df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
    else:
        df = pd.DataFrame([row])
    df.to_csv(f, index=False)


def load_stored(coin):
    f = DATA / f"levels_{coin}.csv"
    if not f.exists():
        return None
    df = pd.read_csv(f)
    if df.empty:
        return None
    last = df.iloc[-1].to_dict()
    last.pop("date", None)
    return {k: float(v) for k, v in last.items()}


# --------------------------------------------------------------------- main ----
def main():
    today = date.today()
    print(f"=== Crypto-Levels-Seed build  {today} ===\n")
    levels, summary, stale_coins = {}, [], []
    for coin, perp, uly in COINS:
        # -- options: the core (fail here => fall back to stored levels) --
        try:
            ch = P.deribit_chain(coin)
            df = ch.df
            struct_df = df[(df["dte"] >= STRUCT_MIN_DTE) & (df["dte"] <= STRUCT_MAX_DTE)]
            med_iv = float(struct_df["iv"].median()) if len(struct_df) else 0.0
            if med_iv < 0.10:
                raise RuntimeError(f"degenerate chain (median IV {med_iv:.3f} < 0.10)")
            struct = gex.compute_levels(struct_df, ch.spot)
            near = gex.compute_levels(df[df["dte"] <= NEAR_MAX_DTE], ch.spot)
            if struct is None:
                raise RuntimeError("no structure chain")
        except Exception as e:  # noqa: BLE001
            stored = load_stored(coin)
            if stored:
                print(f"[skip] {coin}: {e} -> keeping stored levels")
                levels[coin] = stored
                stale_coins.append(coin)
            else:
                print(f"[skip] {coin}: {e} (no stored levels either)")
            continue

        vals = {"FLIP": g(struct, "gamma_flip"), "CW": g(struct, "call_wall"),
                "PW": g(struct, "put_wall"), "CW2": g(struct, "call_wall2"),
                "PW2": g(struct, "put_wall2"), "NCW": g(near, "call_wall"),
                "NPW": g(near, "put_wall"), "NF": g(near, "gamma_flip"),
                "MP": g(struct, "max_pain"), "SPOT": struct["spot"],
                "EM": g(struct, "exp_move_1d"),
                "GEXBN": struct["total_gex"] / 1e9,
                "VAN": (struct.get("total_vanna") or 0.0) / 1e6,
                "VANK": g(struct, "vanna_strike"),
                "CHM": (struct.get("total_charm") or 0.0) / 1e6,
                "CHMK": g(struct, "charm_strike")}

        # -- derivatives snapshot (fail-soft: zeros hide the label line) --
        try:
            b = P.binance_snapshot(perp)
            vals.update({"FUND": b["funding_8h_pct"], "OIU": b["oi_usd_bn"],
                         "OID": b["oi_d24_pct"], "LSR": b["global_ls"],
                         "TLS": b["top_ls"]})
        except Exception as e:  # noqa: BLE001
            print(f"[warn] {coin}: Binance snapshot failed ({e})")
            vals.update({"FUND": 0.0, "OIU": 0.0, "OID": 0.0, "LSR": 0.0, "TLS": 0.0})

        # -- liquidation clusters (fail-soft: zero levels are not drawn) --
        try:
            lq = P.okx_liq_clusters(uly, spot=struct["spot"])
        except Exception as e:  # noqa: BLE001
            print(f"[warn] {coin}: OKX liquidations failed ({e})")
            lq = []
        for i in range(3):
            vals[f"LQ{i + 1}"] = lq[i]["price"] if i < len(lq) else 0.0
            vals[f"LQ{i + 1}D"] = float(lq[i]["dir"]) if i < len(lq) else 0.0

        levels[coin] = vals
        store_levels(coin, today, vals)
        summary.append(
            f"{coin:4s} spot {vals['SPOT']:.0f} | {struct['regime'].upper():7s} "
            f"| Flip {vals['FLIP']:.0f} ({struct['dist_to_flip_pct'] or 0:+.2f}%) "
            f"| CW {vals['CW']:.0f}/{vals['CW2']:.0f} | PW {vals['PW']:.0f}/{vals['PW2']:.0f} "
            f"| EM1d +/-{vals['EM']:.0f} | GEX {vals['GEXBN']:+.2f}bn "
            f"| ATM-IV {struct['atm_iv'] or 0:.0%}")

    if not levels:
        print("\nNOTHING built - all providers failed. Old Pine stays valid.")
        return 1
    note = f" ({'/'.join(stale_coins)}=stored)" if stale_coins else ""
    out = gen_auto_pine(levels, today, note)
    txt = "\n".join(summary)
    print("\n" + txt)
    (ROOT / "today_levels.txt").write_text(
        f"Crypto levels {today}{note}\n{txt}\n", encoding="utf-8")
    print(f"\nPine written: {out.name} -> paste into the TradingView Pine editor, save, FREEZE.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
